
# performance tuning

- name: Ensure swapfile does not already exist
  stat:
    path: "{{ swap_file_path }}"
  register: swapfile_status

- name: Create swapfile of specified size
  command: "fallocate -l {{ swap_file_size }} {{ swap_file_path }}"
  when: not swapfile_status.stat.exists

- name: Set secure permissions on swapfile
  file:
    path: "{{ swap_file_path }}"
    owner: root
    group: root
    mode: 0600

- name: Format the swapfile
  command: mkswap {{ swap_file_path }}

- name: Enable the swapfile
  command: swapon {{ swap_file_path }}

- name: Make swap activation persistent across reboots
  lineinfile:
    path: /etc/fstab
    line: "{{ swap_file_path }} none swap sw 0 0"

- name: Configure swapiness
  sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
    sysctl_set: yes  # Ensure immediate application of the setting
    state: present  

- name: Set vm.swappiness to 10
  sysctl:
    name: vm.swappiness
    value: '10'
    state: present
    reload: yes 

- name: Increase file descriptor limits
  lineinfile:
    path: /etc/security/limits.conf
    line: '* soft nofile 65536'
    create: yes
# doesnt work
# - name: Set CPU governor to performance 
#   shell: cpupower frequency-set -g performance


- name: Optimize network settings
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes 
  with_dict:
    net.core.rmem_max: 16777216
    net.core.wmem_max: 16777216
    net.ipv4.tcp_rmem: 4096 87380 16777216
    net.ipv4.tcp_wmem: 4096 65536 16777216