
- name: steamcmd agreement
  become: true
  shell: |
    echo steam steam/question select "I AGREE" | sudo debconf-set-selections
    echo steam steam/license note '' | sudo debconf-set-selections
- name: Install SteamCMD
  become: true
  apt:
    name: steamcmd
    state: present
    # force_apt_get: yes
    # dpkg_options: 'force-confdef,force-confold'

- name: Create SteamCMD user
  user:
    name: "{{ steamcmd_user }}"
    state: present

- name: Create SteamCMD directory
  file:
    path: "{{ steamcmd_dir }}"
    state: directory
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"

- name: Download SteamCMD
  get_url:
    url: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
    dest: "{{ steamcmd_dir }}/steamcmd_linux.tar.gz"

- name: Extract SteamCMD archive
  unarchive:
    src: "{{ steamcmd_dir }}/steamcmd_linux.tar.gz"
    dest: "{{ steamcmd_dir }}"
    remote_src: yes

- name: Ensure SteamCMD script is executable
  file:
    path: "{{ steamcmd_dir }}/steamcmd.sh"
    mode: 0755